Pages routes auth
deekshithmd/freshbuy-ecommerce-react pull request #1
Opened 2022-03-23 10:24 UTC by deekshithmd

Added Pages, routing to different pages and basic authentication without validation, Please review the code and provide your comments

2022-03-23 10:53 UTC, sushmita12345 commented
- Easily readable & understandable
- Clean code
- There is no breakpoint, you can proceed to merge.

2022-03-23 10:53 UTC, sushmita12345 approved these changes

2022-03-23 11:20 UTC, m26unkwn requested changes
Hey deekshit you can just divide your branches so it would be easy for us to review it.

2022-03-24 04:56 UTC, deekshithmd commented
> Hey deekshit you can just divide your branches so it would be easy for us to review it.

Ok, Since I felt like lagging in proceeding, I made this PR. I will take care while raising PR next time.

2022-03-24 14:24 UTC, merged